#pragma kernel InitPara
#pragma kernel ApplyAndPredicate
#pragma kernel ProjectConstraints 
#pragma kernel UpdateProperty

#include "PBDMath.hlsl"

[numthreads(THREAD_X,THREAD_Y,1)]
void InitPara(uint3 id:  SV_DispatchThreadID)
{   
    uint index = getIndex(id.xy);
    // [fix] when init, w must be 1，and init prePos to avoid frame 1 = NaN
    positions[index] = float4(id.x * L0, 0, id.y * L0, 1.0);
    prePos[index] = positions[index];
    velocities[index] = float3(0,0,0);
    normals[index] = float4(0,1,0,0);
}

[numthreads(THREAD_X,THREAD_Y,1)]
void ApplyAndPredicate(uint3 id:  SV_DispatchThreadID)
{
    if(isPinned(id.xy)) return; // [fix] no prePos for pin
    
    uint index = getIndex(id.xy);
    float3 f = calcExForce(id.xy);
    float3 a = f * rcp(M);
    float3 velocity = getVelocity(index) + a * dt;
    velocities[index] = velocity;
    updateNormal(id.xy);
    
    prePos[index] = positions[index] + float4(velocities[index] * deltaTime, 0);
}

[numthreads(THREAD_X,THREAD_Y,1)]
void ProjectConstraints(uint3 id:  SV_DispatchThreadID)
{
    if(isPinned(id.xy)) return;     // [fix] no constrain on pin
    
    uint index = getIndex(id.xy);
    float3 currPos = getPredicatePosition(index);
    float3 deltaPos = float3(0,0,0);
    uint validCount = 0;    // [fix] take valid constrain counter
    
    for(uint i = 0; i < 12; i ++)
    {
        int2 nId = (int2)id.xy + SpringDirs[i];
        if(isValidateId(nId))
        {
            uint nIndex = getIndex((uint2)nId);
            float3 nPos = getPredicatePosition(nIndex);
            float3 curr2Neighbor = normalize(nPos - currPos);
            float springLength = distance(nPos, currPos);
            float d = restLengths[i/4]; 
            
            deltaPos += 0.5 * (springLength - d) * curr2Neighbor; 
            validCount++;
        }
    }
    
    // [fix] clamp the delta pos to avoid explore, 1.5 is SOR 
    if(validCount > 0)
    {
        prePos[index] += float4(deltaPos / (float)validCount, 0) * 1.5; 
    }

    solveCollision(index);
}

[numthreads(THREAD_X,THREAD_Y,1)]
void UpdateProperty(uint3 id:  SV_DispatchThreadID)
{
    if(isPinned(id.xy)) return;
    
    uint index = getIndex(id.xy);
    velocities[index] = (prePos[index].xyz - positions[index].xyz) / deltaTime;
    // [fix] w === 1.0
    positions[index] = float4(prePos[index].xyz, 1.0); 
}