@startuml Sequence
actor Developer
participant "sh : SpatialHash" as SH
participant "gpuSort : GPUCountSort" as Sort
participant "scan : Scan" as Scan
participant "spatialOffsetsCalc : SpatialOffsetCalculator" as SOC

Developer -> SH : Run()
activate SH

note right of SH: 步骤1：对键值与索引进行排序
SH -> Sort : Run(SpatialIndices, SpatialKeys, maxValue)
activate Sort

Sort -> Scan : Run(countsBuffer)
activate Scan
note right of Scan: 计算前缀和用于排序Scatter
Scan --> Sort : Return
deactivate Scan

Sort --> SH : Return (Keys and Indices are now sorted)
deactivate Sort

note right of SH: 步骤2：基于已排序键值计算偏移量
SH -> SOC : Run(true, SpatialKeys, SpatialOffsets)
activate SOC
SOC --> SH : Return (Offsets are ready)
deactivate SOC

SH --> Developer : Execution Complete
deactivate SH
@enduml