@startuml Sequence3
actor Developer
participant "SpecialHash" as SH
participant "GPURadixSort" as Sort
participant "ComputeHelper" as CH <<static>>
participant "Scan" as Scan
participant "SpatialOffsetCalculator" as SOC

Developer -> SH : Run()
activate SH

note over SH, Sort : Step 1: Run the radix sorting algorithm.
SH -> Sort : Run(SpatialIndices, SpatialKeys)
activate Sort

loop 8 times (For i = 0 to 7)
    note right of Sort : Local radix sorting computation within a block.
    Sort -> CH : Dispatch()
    activate CH
    CH --> Sort
    deactivate CH

    note right of Sort : Calculate the prefix sum of the target count
    Sort -> Scan : Run(DstCounterBuffer)
    activate Scan
    Scan --> Sort
    deactivate Scan

    note right of Sort : Global Scatter allocation
    Sort -> CH : Dispatch()
    activate CH
    CH --> Sort
    deactivate CH
    
    note right of Sort : Swap pointers referencing Buffer
end

Sort --> SH : GPURadixSort Complete
deactivate Sort

note over SH, SOC : Step 2: Calculate the spatial offset
SH -> SOC : Run(true, SpatialKeys, SpatialOffsets)
activate SOC

SOC -> CH : Dispatch()
activate CH
CH --> SOC
deactivate CH

SOC -> CH : Dispatch()
activate CH
CH --> SOC
deactivate CH

SOC --> SH : Offsets Calculated
deactivate SOC

SH --> Developer : Execution Complete
deactivate SH
@enduml