#pragma kernel InBlockRadix
#pragma kernel GlobalScatter

#include "./RadixHelper.hlsl"

[numthreads(THREAD_NUM_X, 1, 1)]
void InBlockRadix(uint GI : SV_GroupIndex, uint3 DTid : SV_DispatchThreadID, uint3 Gid : SV_GroupID)
{
    uint digit = get4Bits(InputKeys[DTid.x], currIteration);
    
    [unroll(RADIX_R)]
    for (uint r = 0; r < RADIX_R; ++r)
    {
        localPrefix[GI] = (digit == r ? 1 : 0);
        GroupMemoryBarrierWithGroupSync();
        PrefixSumLocal(GI, r * g_BlocksNums + Gid.x);
        // now localPrefix[] is EScan of current block.
        
        if(digit == r)  GlobalPSum[DTid.x] = localPrefix[GI];
        GroupMemoryBarrierWithGroupSync();
    }
}

[numthreads(THREAD_NUM_X, 1, 1)]
void GlobalScatter(uint3 DTid : SV_DispatchThreadID,uint3 Gid:SV_GroupID)
{
    uint digit = get4Bits(InputKeys[DTid.x], currIteration);

    uint counterIndex = digit * g_BlocksNums + Gid.x;
    uint globalOffset = GlobalPSum[DTid.x] + DstCounter[counterIndex];
    SortedKeys[globalOffset] = InputKeys[DTid.x];
    SortedIndex[globalOffset] = InputIndex[DTid.x];
}